twilio:
  phone_number: '7788002767'
  account_sid: 'AC5e98a9a0d24a4dcbbc3126473d142d35'
  auth_token: 'da2c9e85efafa8848b3e705ae3a2afe9'
demo_mode: false
deployment:
  server: 'localhost'
  app_name: 'weltel'
  deploy_to: '/www/weltel' 
  app_repo: "ssh://git@dev.verticallabs.ca/git/mambo/apps/weltel.git"
  app_branch: '3.0'
  internal_host: "http://localhost:3000"
  rails_env: 'production'
  app_root: '/www/weltel/current'
  working_directory: "/www/weltel/shared"
  log_directory: "/www/weltel/shared/log"
  processes:
    unicorn:
      start: "bundle exec unicorn_rails -E #{RAILS_ENV} -c #{PWD}/config/unicorn.rb -D"
      stop: "kill -QUIT $(cat #{PID_FILE})"
      restart: "kill -USR2 $(cat #{PID_FILE})"
      workers: 2
      port: 80
    dj:
      start: "bundle exec rake jobs:work"
      daemonize: true
  monitoring:
    log_file: "monitoring.log"
    group_name: mambo
  uid: web
  gid: web
