twilio_phone_number: '7788002767'
alert_phone_numbers: ['7783175526']
deployment:
  rails_env: 'development'
  app_root: '/home/paul/mambo/apps/weltel'
  working_directory: "/home/paul/mambo/apps/weltel/tmp"
  log_directory: "/home/paul/mambo/apps/weltel/log"
  monitoring:
    log_file: "monitoring.log"
    group_name: mambo
    uid: paul
    gid: paul
    processes:
      - name: dj
        start: "rake jobs:work"
      - name: unicorn
        start: "bundle exec unicorn_rails -E #{RAILS_ENV} -c #{PWD}/config/unicorn.rb -D" 
        stop: "kill -QUIT #{PID}"
        restart: "kill -USR2 #{PID}"
