twilio:
  phone_number: '7788002767'
  account_sid: 'AC5e98a9a0d24a4dcbbc3126473d142d35'
  auth_token: 'da2c9e85efafa8848b3e705ae3a2afe9'
demo_enabled: true
time_zone: "Pacific Time (US & Canada)"
update:
  refresh: 10
deployment:
  server: 'localhost'
  app_name: 'weltel'
  app_repo: "https://github.com/weltel/weltel.git"
  app_branch: 'ar'
  deploy_to: '/home/paul/dev/weltel' 
  app_root: '/home/paul/dev/weltel'
  working_directory: "/home/paul/dev/weltel/tmp"
  internal_host: "http://localhost:3000"
  rails_env: 'development'
  log_directory: "/home/paul/dev/weltel/log"
  processes:
    unicorn:
      start: "bundle exec unicorn_rails -E #{RAILS_ENV} -c #{APP_ROOT}/config/unicorn.rb -D"
      stop: "kill -QUIT #{PID}"
      restart: "kill -USR2 #{PID}"
      workers: 2
      port: 3000
      process_name: 'mambo_unicorn'
    dj:
      start: "bundle exec rake jobs:work"
      daemonize: true
    gammu:
      config_file: '/home/paul/dev/weltel/config/gammurc'
      start: 'gammu-smsd -c /home/paul/dev/weltel/config/gammurc'
      stop: "kill -TERM #{PID}" 
      daemonize: true
  monitoring:
    log_file: "monitoring.log"
    group_name: 'mambo'
  uid: 'paul'
  gid: 'paul'
