development:
  unicorn: unicorn_rails
  app_root: /home/paul/weltel
  app_runtime: /home/paul/weltel/tmp
  workers: 1
  port: 3000

test:
  unicorn: unicorn_rails
  app_root: /home/paul/weltel
  app_runtime: /home/paul/weltel/tmp
  workers: 1
  port: 3000

production:
  unicorn: /www/weltel/shared/bundle/ruby/1.9.1/bin/unicorn_rails
  app_root: /www/weltel/current
  app_runtime: /www/weltel/shared
  workers: 2
  port: 8080
